```{r}
options(future.globals.maxSize= 8912896000)
Sys.setenv(PATH = "/Users/rf/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/ncbi/blast/bin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/RStudio.app/Contents/MacOS/postback")
rextendr::clean()
rextendr::document()
devtools::load_all(".")
```

```{r}
library(tidyverse)
library(Seurat)
library(SCoreRust)
so <- pbmc_small
so <- readRDS("/Users/rf/hsieh/ffpe_spatial_all_harmony.rds")
DefaultAssay(so) <- "RNA"
# so <- UpdateSeuratObject(so)
paths <- Seurat::cc.genes.updated.2019
mock_paths <- map(paths, function(x) {
  intersect(rownames(so), x)
})
# testing on a small example
mock_paths <- map(1:3000, function(x) sample(rownames(so), 20 + x%%10))
mat <- as.matrix(so@assays$Spatial@data)
gs <- rownames(so@assays$Spatial@data)
future::plan(future::multisession, workers = 4)

res <- bench::mark(
  SCore = furrr::future_map(mock_paths, function(x) {
    SCoreRust::calc_modulescore(mat,
                     x,
                     gs,
                     nbin = 24,
                     nsample = 100,
                     nthread = 0)})
)

res <- bench::mark(
  #Seurat = AddModuleScore(so, features = mock_paths),
  #SCore = calc_module_scores(mat, mock_paths, precal = F),
  SCore_pre = calc_module_scores(mat, mock_paths),
  iterations = 3,
  check = FALSE,
  memory = F
)
saveRDS(res, "/Users/rf/SCorerustR/10kx3000_bench2.rds")
b <- ggplot(res %>%
         mutate(expression = as.character(expression)) %>%
         select(expression, time) %>%
         unnest_longer(time), 
       aes(x = expression, y = time)) +
  geom_boxplot(aes(fill = expression), outlier.shape = NA) +
  geom_jitter(size = 0.5, alpha = 0.5) +
  theme_classic() +
  ylab("time (s)") +
  ylim(c(0, NA)) +
  NoLegend()
# yielding similar scores, note that the random sampling isn't exactly the same
resa1 <- AddModuleScore(so, features = mock_paths[[1]])$Cluster1
resa2 <- AddModuleScore(so, features = mock_paths[[2]])$Cluster1
resa3 <- AddModuleScore(so, features = mock_paths[[3]])$Cluster1
resb <- calc_module_scores(mat, mock_paths)
resbre <- calc_module_scores(mat, mock_paths[3], nrep = 100)

resbb <- calc_modulescore(mat,
                         mock_paths[[2]],
                         rownames(mat),
                         nbin = 24,
                         nsample = 100, 
                         nthread = 1)
resc <- calc_modulescore(as.matrix(so@assays$Spatial@data),
                         mock_paths[[2]],
                         rownames(so@assays$Spatial@data),
                         nbin = 20,
                         nsample = 10)
a <- ggplot(data.frame(Seurat = resbre[1,], SCore = resa3), aes(x = Seurat, y = SCore)) + 
  geom_point(size = 1) +
  theme_classic() +
  coord_fixed()
ggsave("bench1.png", cowplot::plot_grid(a, b, rel_widths = c(2, 1)), width = 6, height = 3)
```

```{r}
mat2 <- do.call(cbind, list(mat, mat, mat, mat, mat, mat, mat, mat, mat))
res <- bench::mark(
  R = {data.avg <- Matrix::rowMeans(x = mat); data.avg[order(data.avg)]} %>% names(),
  rust = SCoreRust::order_expr(mat, gs, 1),
  rust2 = SCoreRust::order_expr(mat, gs, 2),
  rust4 = SCoreRust::order_expr(mat, gs, 4),
  rust8 = SCoreRust::order_expr(mat, gs, 8),
  iterations = 3,
  check = F
)
```

```{r}
ord <- {data.avg <- Matrix::rowMeans(x = mat); data.avg[order(data.avg)]} %>% names()
data.cut <- cut_number(x = data.avg + rnorm(n = length(data.avg))/1e30, n = 24, labels = FALSE, right = FALSE)
names(x = data.cut) <- names(x = data.avg)

map(mock_paths, function(features.use) {
# seurat
ctrl.use <- c()
for (j in 1:length(x = features.use)) {
  temp_bin <- data.cut[which(x = data.cut == data.cut[features.use[j]])]
  temp <- names(x = sample(
      x = temp_bin,
      size = 100,
      replace = FALSE
    ))
  ctrl.use <- c(
    ctrl.use,
    temp
  ) 
}
ctrl.use <- list(unique(ctrl.use))
ctrl.scores <- matrix(
  data = numeric(length = 1L),
  nrow = 1,
  ncol = ncol(mat)
)
for (i in 1:length(ctrl.use)) {
  ctrl.scores[i, ] <- Matrix::colMeans(x = mat[ctrl.use[[1]], ])
}
})

# precal
bac <- matrix(
  data = numeric(length = 1L),
  nrow = 20 * max(data.cut),
  ncol = ncol(mat)
)
for (x in 1:max(data.cut)) {
  for (i in 1:20) {
    temp_bin <- data.cut[which(data.cut == x)]
    temp <- names(x = sample(
        x = temp_bin,
        size = 100,
        replace = FALSE
      ))
    bac[(i - 1) * 20 + x, ] <- Matrix::colMeans(x = mat[temp, ])
  }
}
map(mock_paths, function(features.use) {
bac1 <- matrix(
  data = numeric(length = 1L),
  nrow = length(features.use),
  ncol = ncol(mat)
)
for (j in 1:length(x = features.use)) {
  ind <- sample(20, 1) + 20 * (data.cut[features.use[j]] - 1)
  bac1[j, ] <- bac[ind,]
}
Matrix::colMeans(bac1)
})

# bench
res <- bench::mark(
  seurat = {map(mock_paths, function(features.use) {
  
# seurat
ctrl.use <- c()
for (j in 1:length(x = features.use)) {
  temp_bin <- data.cut[which(x = data.cut == data.cut[features.use[j]])]
  temp <- names(x = sample(
      x = temp_bin,
      size = 100,
      replace = FALSE
    ))
  ctrl.use <- c(
    ctrl.use,
    temp
  ) 
}
ctrl.use <- list(unique(ctrl.use))
ctrl.scores <- matrix(
  data = numeric(length = 1L),
  nrow = 1,
  ncol = ncol(mat)
)
for (i in 1:length(ctrl.use)) {
  ctrl.scores[i, ] <- Matrix::colMeans(x = mat[ctrl.use[[1]], ])
}
})},
precal = {bac <- matrix(
  data = numeric(length = 1L),
  nrow = 20 * max(data.cut),
  ncol = ncol(mat)
)
for (x in 1:max(data.cut)) {
  for (i in 1:20) {
    temp_bin <- data.cut[which(data.cut == x)]
    temp <- names(x = sample(
        x = temp_bin,
        size = 100,
        replace = FALSE
      ))
    bac[(i - 1) * 20 + x, ] <- Matrix::colMeans(x = mat[temp, ])
  }
}
map(mock_paths, function(features.use) {
bac1 <- matrix(
  data = numeric(length = 1L),
  nrow = length(features.use),
  ncol = ncol(mat)
)
for (j in 1:length(x = features.use)) {
  ind <- sample(20, 1) + i * (data.cut[features.use[j]] - 1)
  bac1[j, ] <- bac[ind,]
}
Matrix::colMeans(bac1)
})},
iterations = 2,
check = F
)
```


```{r}
remotes::install_github("https://github.com/raysinensis/SCore-rust/", force = TRUE)
SCorerustR::calc_modulescore()
pass_features(c("ZFP36", "UPF1"))
pass_mat(as.matrix(SeuratObject::pbmc_small@assays$RNA@data))
```

```{r}
res2 <- readRDS("/Users/rf/SCorerustR/10kx3000_bench.rds")
res <- readRDS("/Users/rf/SCorerustR/10kx3000_bench2.rds")
b <- ggplot(res %>%
              mutate(expression = as.character(expression)) %>%
              filter(expression %in% c("SCore_pre")) %>% 
              mutate(expression = ifelse(expression == "SCore_pre", "SCoreRust", expression)) %>% 
              bind_rows(res2 %>% mutate(expression = as.character(expression)) %>%
              filter(expression %in% c("Seurat"))) %>% 
              select(expression, time) %>%
              unnest_longer(time) %>% 
              bind_rows(data.frame(expression = "Scanpy", time = bench::as_bench_time(2653))) %>% 
              bind_rows(data.frame(expression = "Scanpy", time = bench::as_bench_time(2680))) %>% 
              bind_rows(data.frame(expression = "Scanpy", time = bench::as_bench_time(2583))) %>% 
              bind_rows(data.frame(expression = "SCoreRust-re", time = bench::as_bench_time(89.28348))) %>% 
              bind_rows(data.frame(expression = "SCoreRust-re", time = bench::as_bench_time(106.66742))) %>% 
              bind_rows(data.frame(expression = "SCoreRust-re", time = bench::as_bench_time(119.99710))) %>% 
              mutate(expression = factor(expression, levels = c("Seurat", "Scanpy", "SCoreRust", "SCoreRust-re"))),
       aes(x = expression, y = time)) +
  geom_boxplot(aes(fill = expression), outlier.shape = NA, size = 0.2) +
  geom_jitter(size = 0.5, alpha = 0.5, height = 0, width = 0.25) +
  theme_classic() +
  ylab("time (s)") +
  ylim(c(0, 4000)) +
  NoLegend()
```

