# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_SCorerustR_wrappers", use_symbols = TRUE, package_name = "SCorerustR")

#' @docType package
#' @usage NULL
#' @useDynLib SCorerustR, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
calc_modulescore <- function(mat, features, allfeatures, nbin, nsample, nthread) .Call(wrap__calc_modulescore, mat, features, allfeatures, nbin, nsample, nthread)

#' Return string `"Hello world!"` to R.
#' @export
pass_features <- function(features) invisible(.Call(wrap__pass_features, features))

#' Return string `"Hello world!"` to R.
#' @export
pass_mat <- function(mat) invisible(.Call(wrap__pass_mat, mat))

