# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_SCoreRust_wrappers", use_symbols = TRUE, package_name = "SCoreRust")

#' @docType package
#' @usage NULL
#' @useDynLib SCoreRust, .registration = TRUE
NULL

#' Calculate pathway scoring, similar to Seurat::AddModuleScore
#' @export
calc_modulescore <- function(mat, features, allfeatures, nbin, nsample, nthread) .Call(wrap__calc_modulescore, mat, features, allfeatures, nbin, nsample, nthread)

#' Test passing gene list from R.
#' @export
pass_features <- function(features) invisible(.Call(wrap__pass_features, features))

#' Test passing expr matrix from R.
#' @export
pass_mat <- function(mat) invisible(.Call(wrap__pass_mat, mat))

