# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_SCorerustR_wrappers", use_symbols = TRUE, package_name = "SCorerustR")

#' @docType package
#' @usage NULL
#' @useDynLib SCorerustR, .registration = TRUE
NULL

#' Pathway scoring for 1 pathway
#' @export
calc <- function() .Call(wrap__calc)

